# Generated by Django 2.0.6 on 2018-10-21 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20181010_1404'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='userid',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='userpurchase',
            old_name='userid',
            new_name='email',
        ),
        migrations.AddField(
            model_name='userpurchase',
            name='month',
            field=models.IntegerField(null=True),
        ),
    ]
